language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8
      - xorg-dev
            
compiler:
  - gcc
  - clang

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export GENIE_FOLDER="linux"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8" COMPILER="gcc" TOOLCHAIN="linux-gcc-8" GMAKE_FOLDER="gmake-linux"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang" COMPILER="clang" TOOLCHAIN="linux-clang" GMAKE_FOLDER="gmake-linux-clang"; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export GENIE_FOLDER="darwin" TOOLCHAIN="osx" GMAKE_FOLDER="gmake-osx"; fi

script:
  - bin/$GENIE_FOLDER/genie --gcc=$TOOLCHAIN gmake
  - cd build/projects/$GMAKE_FOLDER
  - make config=debug64

os:
  - linux
  - osx
  
matrix:
  exclude:
    - os: osx
      compiler: gcc
