language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - xorg-dev

before_script:
  - git clone --depth 1 https://github.com/bkaradzic/bx ../bx
  - git clone --depth 1 https://github.com/hugoam/bimg ../bimg
  - git clone --depth 1 https://github.com/hugoam/bgfx ../bgfx

matrix:
  include:
    - os: linux
      compiler: gcc
      script:
          - bin/linux/genie --gcc=linux-gcc-8 gmake
          - cd build/projects/gmake-linux-gcc-8
          - time make config=debug64
    - os: linux
      compiler: clang
      script:
          - bin/linux/genie --gcc=linux-clang gmake
          - cd build/projects/gmake-linux-clang
          - time make config=debug64
    - os: osx
      compiler: clang
      osx_image: xcode10
      script:
          - bin/darwin/genie --gcc=osx gmake
          - cd build/projects/gmake-osx
          - time make config=debug64
    - os: windows
      script:
          - bin\windows\genie vs2017
          - cd build\projects\vs2017
          - MSBuild.exe two.sln


